### ISSUE TITLE
ember-cli-postcss support

### ISSUE THREAD

**Issue by oliverlj** [ember-bootstrap/ember-bootstrap#1155]
Hi guys,

I have successfully integrated ember-cli-postcss / sass on 4.0.0-rc3 but with this configuration :

//ember-cli-build.js
```json
postcssOptions: {
      compile: {
        enabled: true,
        extension: 'scss',
        parser: require('postcss-scss'),
        plugins: [
          {
            module: require('@csstools/postcss-sass'),
            options: {
              includePaths: [
                'node_modules/admin-lte/dist/css',
                'node_modules/admin-lte/plugins',
                'node_modules/bootstrap/scss',
              ],
            },
          },
        ],
      },
    },
```

//app/styles/app.scss
```scss
@import 'bootstrap';
@import 'adminlte';
```

I cannot include @import "ember-bootstrap/bootstrap"; as specified in the docs.

is this the way to go ?

**Comment by jelhan** [comment]
Awesome. Thanks for sharing. I wanted to do that myself for a long time. Are you using PurgeCSS as well?

> I cannot include @import "ember-bootstrap/bootstrap"; as specified in the docs.
>
> is this the way to go ?

Ember Bootstrap pushes the Bootstrap SASS files into the broccoli tree for styles: https://github.com/kaliber5/ember-bootstrap/blob/3ac25920e0cfa783041391fa9a4e98cd4f477a1b/index.js#L203-L209

I guess ember-cli-postcss does not use that tree but works independently from broccoli. But that shouldn't be a problem as long as you are able to import bootstrap in another way. Ember Bootstrap is only pushing that SASS into the styles tree to make the developers live easier. Otherwise everyone would need to add bootstrap package to `includePaths` of `ember-cli-sass`. Your approach seems to be fine. It only requires a little bit more manual work as Ember Bootstrap does not provide the PostCSS integration out of the box as it does for plain SASS.

You may want to set `importBootstrapCSS` to `false`. It defaults to `true` unless a supported CSS predecessor is detected. As Ember Bootstrap does not support `ember-cli-postcss` it may wrongly import Bootstrap CSS if not prevented manually.

**Comment by oliverlj** [comment]
I have begun to work on an admin-lte addon : https://gitlab.com/oliverlj/admin-lte-ember

I tried purgecss as well, but unsuccessfully. This is due purgecss look in your app hbs but not in node-modules/addon/*.hbs. If someone find a way, it should work. I saw embroider is looking in that way : https://discuss.emberjs.com/t/trouble-using-postcss-purgecss-with-ember-cli-postcss/16623/2

**Comment by jelhan** [comment]
> I tried purgecss as well, but unsuccessfully. This is due purgecss look in your app hbs but not in node-modules/addon/*.hbs.

Oh. I hoped it's looking in the app tree used to build the application and following the prototype chain and template imports for components. But did you tried explicitly adding the ember bootstrap components to the array passed to postcss as `content` option?

So something like this:

```js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const purgecss = require('@fullhuman/postcss-purgecss');

module.exports = function (defaults) {
  const app = new EmberApp(defaults, {
    postcssOptions: {
      filter: {
        enabled: true,
        plugins: [
          {
            module: purgecss,
            options: {
              content: [
                // consider components and other templates provided by the application files
                './app/index.html',
                './app/templates/*.hbs',
                './app/components/.js',
                './app/components/.hbs',

                // consider components provided by Ember Bootstrap
                './node_modules/ember-bootstrap/addon/templates/*.hbs',
                './node_modules/ember-bootstrap/addon/components/*.hbs',
                './node_modules/ember-bootstrap/addon/components/*.js',
              ],
            }
          }
        ]
      }
    }
  });
  return app.toTree();
};
```

**Comment by oliverlj** [comment]
I have almost a working configuration

```js
filter: {
        enabled: true,
        plugins: [
          {
            module: require('@fullhuman/postcss-purgecss'),
            options: {
              content: [
                // add extra paths here for components/controllers which include tailwind classes
                './app/index.html',
                './app/components/**/*.hbs',
                './app/templates/**/*.hbs',
                './app/pods/**/*.hbs',

                './node_modules/admin-lte-ember/addon/**/*.hbs',
                './node_modules/admin-lte-ember/addon/**/*.ts',

                './node_modules/ember-bootstrap/addon/templates/*.hbs',
                './node_modules/ember-bootstrap/addon/components/*.hbs',
                './node_modules/ember-bootstrap/addon/components/*.js',
              ],
              defaultExtractor: (content) => content.match(/[A-Za-z0-9-_:/]+/g) || [],
            },
          },
        ],
      },
```

Missing things now are class concatenate by ember-bootstrap (example : btn-danger)

**Comment by oliverlj** [comment]
I have published an addon for the postcss configuration with optional purgecss ! :)
https://www.npmjs.com/package/ember-bootstrap-postcss

I think this issue can be close now
