### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap#1743]
The Ember ecosystem is moving towards TypeScript more and more. I think we should consider it for Ember Bootstrap as well.

I see two main benefits from doing so:

1. Ease writing of API docs: Many developers are more familiar with writing TypeScript interfaces than using JSDoc.
2. It should provide a better integration with ecosystem tooling in the mid- to long-term. I'm especially looking towards editor support for autocompletion and similar features in templates.

I guess the main blocker is to figure out how we could generate API docs based on TypeScript interfaces and TSDoc and integrate it well with our existing docs site.

**Comment by simonihmig** [comment]
Personally, I have no concerns about this, as all of our (closed source) day-time job work is TS, for many years. However, a concern we might want to consider is whether this increases the barrier for external contributors?

> The Ember ecosystem is moving towards TypeScript more and more

Admittedly, this concern had a greater weight years ago, so I am not saying this outweighs the benefits...

>  I'm especially looking towards editor support for autocompletion and similar features in templates.

Yeah, so that was my other concern: as things stand today, having types for components has very little benefit for consumers *today*. Of course, typed templates would be a game changer here! 😍. But we are not there yet...

**Comment by simonihmig** [comment]
> Of course, typed templates would be a game changer here! 😍. But we are not there yet...

I played with Glint a bit over the last week or so, and must say that I'm quite excited about it. It works pretty well already. So yeah, this topic should get more attention definitively!

> I guess the main blocker is to figure out how we could generate API docs based on TypeScript interfaces and TSDoc and integrate it well with our existing docs site.

I would like to add that migrating all component to Glimmer components might also be helpful. While we have all code already migrated to native classes and decorators (one of the main preconditions to migrate to TS), I wouldn't want to spent much time on adding types as Ember components, before having them migrated to Glimmer...

**Comment by jelhan** [comment]
Closing in favor of #2053.
